name: Install & Test classy-config
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '*.md'

env:
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  node:
    name: Node.js
    strategy:
      matrix:
        node-version: [^12.0.0, ^14.0.0, ^15.0.0]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i pnpm@latest -g

      - run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - run: pnpm install

      - run: pnpm test:coverage
        if: matrix.os == 'ubuntu-latest'

      - run: pnpm test:coverage -- --use-spawn-wrap
        if: matrix.os == 'windows-latest'

      - uses: codecov/codecov-action@v1

  typescript:
    name: Check typescript types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - run: npm i pnpm@latest -g

      - run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - run: pnpm install

      - run: pnpm ts:check

  lint:
    name: ESLint source files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - run: npm i pnpm@latest -g

      - run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - run: pnpm install

      - run: pnpm lint:check
